import pprint
import random
from random import randint
#Products generated by AI
products = ["Mechanical Keyboard", "Wireless Mouse", "Desk Mat", "Monitor Stand", "Notebook", "Gel Pen Set", "USB-C Hub", "Webcam"]
prices = [129.00, 49.00, 19.00, 39.00, 9.00, 12.00, 59.00, 89.00]
categories = ["Electronics", "Electronics", "Accessories", "Accessories", "Stationery", "Stationery", "Electronics", "Electronics"]
item_tags = ["product_name", "price", "category"]
#Customers generated by AI
customers = ["Anna Andersson", "Björn Berg", "Cecilia Carlsson", "David Dahl", "Elin Eriksson"]
emails = ["anna@example.com", "bjorn@example.com", "cecilia@example.com", "david@example.com", "elin@example.com"]
ids = ["C-001", "C-002", "C-003", "C-004", "C-005"]
customer_tags = ["name", "email", "customer_id"]
#Optional order information
shipping = ["Standard Shipping", "Free Shipping", "Express Shipping"]
discount = [0.1, 0.15, 0.2, 0.25]
gift_message = ["Happy Birthday!", "Happy Anniversary!", "Merry Christmas!"]
delivery = ["Leave at the door", "Leave at front desk", "Knock on the door"]
opt_list = [shipping, discount, gift_message, delivery]
opt_tag = ["Shipping", "Discount", "Gift Message", "Delivery"]

#A function that creates a list of dictionaries
def create(a,b,c,d,e,f):
    dict = []
    for i in range(0,len(d)):
        temp = {
            a: d[i],
            b: e[i],
            c: f[i]
        }
        dict.append(temp)
    return(dict)

product_dict = create(*item_tags,products,prices,categories)
#pprint.pprint(product_dict, indent=4, width=60)
customer_dict = create(*customer_tags,customers,emails,ids)
#pprint.pprint(customer_dict, indent=4, width=60)
#Creates a new order
def new_order(order_id, name, email, customer_id, products,**kwargs):
    order = {
        "Order ID" : order_id,
        "Name" : name,
        "Email" : email,
        "Customer ID" : customer_id
        }
    for key, value in kwargs.items():
        order[key] = value
    subtotal = 0
    for i in range(len(products)):
        order["Product " + str(i+1)] = products[i]
        subtotal += products[i]["price"]
    if "Discount" in kwargs:
        subtotal = subtotal*(1-kwargs["Discount"])
    order["Subtotal"] = subtotal
    return order
# Generates a list containing 5 randomised orders
def generate():
    orders = []
    for i in range(0,5):
        order_id = "Order 000" + str(i+1)
        rand_cust = customer_dict[randint(0,len(customer_dict)-1)]
        customer = [rand_cust["name"], rand_cust["email"], rand_cust["customer_id"]]
        products = random.sample(product_dict, randint(0,len(product_dict)-1))
        other = {}
        rand_opt = random.sample(range(0,len(opt_tag)), randint(0,len(opt_tag)))
        for opt in rand_opt:
            other[opt_tag[opt]] = opt_list[opt][randint(0,len(opt_list[opt])-1)]
        orders.append(new_order(order_id,*customer,products,**other))
    return(orders)


orders=generate()

pprint.pprint(list(enumerate(orders, start=1)), indent=4, width=60)